version: '3'

services:
  visualizer:
    image: dockersamples/visualizer:latest
    ports:
      - "8090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  master:
    image: locustio/locust:latest
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master
    networks:
      - mynetwork

  worker:
    image: locustio/locust:latest
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
    networks:
      - mynetwork
    deploy:
      replicas: 2

networks:
  mynetwork:
    driver: overlay
